<Project>

  <PropertyGroup>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>

    <!-- AOT trimming preparation -->
    <IsAotCompatible>true</IsAotCompatible>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>

    <!-- Source metadata -->
    <Authors>LumiBear Studio</Authors>
    <Company>LumiBear Studio</Company>
    <Copyright>© 2026 LumiBear Studio. All rights reserved.</Copyright>
    <Product>OtterZip</Product>
    <Version>1.2.4</Version>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Prevent implicit transitive package references from polluting AOT graph -->
    <DisableTransitiveProjectReferences>false</DisableTransitiveProjectReferences>
  </PropertyGroup>

</Project>
